/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejemplopoo.ventanas;

import ejemplopoo.elementos.Producto;
import java.awt.BorderLayout;
import paneles.panelCupon;
import paneles.panelLogin;
import paneles.panelMostrarProductos;
import paneles.panelProducto;

/**
 *
 * @author edush
 */
public class ventana extends javax.swing.JFrame {

    /**
     * Creates new form ventana2
     */
    panelLogin log = new panelLogin();
    panelProducto ppro = new panelProducto();
    panelCupon pcup = new panelCupon();
    panelMostrarProductos pmpro = new panelMostrarProductos();
    
    public ventana() {
        initComponents();        
        cambiarPanel(log);
        panelOpciones.setVisible(false);
        this.setTitle("Edu 18/02/2023");
    }
    
    private void cambiarPanel(javax.swing.JPanel miPanel){
        miPanel.setSize(680,320);
        miPanel.setLocation(0,0);        
        panelBase.removeAll();
        panelBase.add(miPanel, BorderLayout.CENTER);
        panelBase.revalidate();
        panelBase.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBase = new javax.swing.JPanel();
        panelAbajo = new javax.swing.JPanel();
        ingresologin = new javax.swing.JButton();
        etiquetaError = new javax.swing.JLabel();
        panelOpciones = new javax.swing.JPanel();
        mostrarProductos = new javax.swing.JButton();
        mostrarCodigos = new javax.swing.JButton();
        irAProducto = new javax.swing.JButton();
        irADescuento = new javax.swing.JButton();
        ventas = new javax.swing.JButton();
        reportes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBase.setBackground(new java.awt.Color(51, 102, 0));

        javax.swing.GroupLayout panelBaseLayout = new javax.swing.GroupLayout(panelBase);
        panelBase.setLayout(panelBaseLayout);
        panelBaseLayout.setHorizontalGroup(
            panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 995, Short.MAX_VALUE)
        );
        panelBaseLayout.setVerticalGroup(
            panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );

        panelAbajo.setBackground(new java.awt.Color(0, 153, 153));

        ingresologin.setText("Ingresar");
        ingresologin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresologinActionPerformed(evt);
            }
        });

        etiquetaError.setText("...");

        javax.swing.GroupLayout panelAbajoLayout = new javax.swing.GroupLayout(panelAbajo);
        panelAbajo.setLayout(panelAbajoLayout);
        panelAbajoLayout.setHorizontalGroup(
            panelAbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAbajoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(ingresologin)
                .addGap(18, 18, 18)
                .addComponent(etiquetaError)
                .addContainerGap(338, Short.MAX_VALUE))
        );
        panelAbajoLayout.setVerticalGroup(
            panelAbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAbajoLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(panelAbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingresologin)
                    .addComponent(etiquetaError))
                .addGap(32, 32, 32))
        );

        panelOpciones.setBackground(new java.awt.Color(153, 153, 153));

        mostrarProductos.setText("Mostrar Productos");
        mostrarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarProductosActionPerformed(evt);
            }
        });

        mostrarCodigos.setText("Mostrar Codigos");

        irAProducto.setText("Volver a Producto");
        irAProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irAProductoActionPerformed(evt);
            }
        });

        irADescuento.setText("Volver a Cupones");
        irADescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irADescuentoActionPerformed(evt);
            }
        });

        ventas.setText("Ventas");
        ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventasActionPerformed(evt);
            }
        });

        reportes.setText("Generar Reportes");

        javax.swing.GroupLayout panelOpcionesLayout = new javax.swing.GroupLayout(panelOpciones);
        panelOpciones.setLayout(panelOpcionesLayout);
        panelOpcionesLayout.setHorizontalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(irAProducto)
                    .addComponent(irADescuento))
                .addGap(18, 18, 18)
                .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOpcionesLayout.createSequentialGroup()
                        .addComponent(mostrarProductos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ventas))
                    .addGroup(panelOpcionesLayout.createSequentialGroup()
                        .addComponent(mostrarCodigos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(reportes)))
                .addContainerGap())
        );
        panelOpcionesLayout.setVerticalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(irAProducto)
                    .addComponent(mostrarProductos)
                    .addComponent(ventas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(irADescuento)
                    .addComponent(mostrarCodigos)
                    .addComponent(reportes))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelAbajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAbajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresologinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresologinActionPerformed
        // TODO add your handling code here:
        if(log.getUsuario().equals("2023") && log.getClave().equals("2023")){
            cambiarPanel(ppro);
            panelAbajo.setVisible(false);
            panelOpciones.setVisible(true);
        }else{
            etiquetaError.setText("Usuario o Clave incorrectas, intente nuevamente");
        }       
               
    }//GEN-LAST:event_ingresologinActionPerformed

    private void ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ventasActionPerformed

    private void mostrarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarProductosActionPerformed
        // TODO add your handling code here:
        String textoProductos="";
        System.out.println("********** Productos en Stock **********");
        for(int i=0; i<ppro.getListaProductos().size();i++){
            Producto temporal = new Producto();
            temporal = ppro.getListaProductos().get(i);
            textoProductos = textoProductos+"Producto: "+temporal.getNombre()+" -> Precio: "+temporal.getPrecio()+'\n';
            System.out.println("Producto: "+temporal.getNombre()+" -> Precio: "+temporal.getPrecio());
        }
        pmpro.setTextArea(textoProductos);
        cambiarPanel(pmpro);
    }//GEN-LAST:event_mostrarProductosActionPerformed

    private void irADescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irADescuentoActionPerformed
        // TODO add your handling code here:
        cambiarPanel(pcup);
    }//GEN-LAST:event_irADescuentoActionPerformed

    private void irAProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irAProductoActionPerformed
        // TODO add your handling code here:
        cambiarPanel(ppro);
    }//GEN-LAST:event_irAProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    
    /**
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        

        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana().setVisible(true);
            }
        });
    }
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiquetaError;
    private javax.swing.JButton ingresologin;
    private javax.swing.JButton irADescuento;
    private javax.swing.JButton irAProducto;
    private javax.swing.JButton mostrarCodigos;
    private javax.swing.JButton mostrarProductos;
    private javax.swing.JPanel panelAbajo;
    private javax.swing.JPanel panelBase;
    private javax.swing.JPanel panelOpciones;
    private javax.swing.JButton reportes;
    private javax.swing.JButton ventas;
    // End of variables declaration//GEN-END:variables
}
