/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejemplopoo.ventanas;

import ejemplopoo.elementos.Cuenta;
import ejemplopoo.elementos.Producto;
import ejemplopoo.elementos.Region;
import ejemplopoo.paneles.panelCuenta;
import java.awt.BorderLayout;
import ejemplopoo.paneles.panelCupon;
import ejemplopoo.paneles.panelLogin;
import ejemplopoo.paneles.panelMostrarProductos;
import ejemplopoo.paneles.panelProducto;
import ejemplopoo.paneles.panelRegion;
import ejemplopoo.paneles.panelVentas;
import ejemplopoo.paneles.prueba;

/**
 *
 * @author edush
 */
public class ventana extends javax.swing.JFrame {

    /**
     * Creates new form ventana2
     */
    private panelLogin log = new panelLogin();
    private panelProducto ppro = new panelProducto();
    private panelCupon pcup = new panelCupon();
    private panelMostrarProductos pmpro = new panelMostrarProductos();
    private panelVentas pv = new panelVentas();
    private panelCuenta pcue = new panelCuenta();
    private String rutaFotoActual = "";
    private prueba pru = new prueba();
    private panelRegion pare = new panelRegion();
    
    // regiones
    private Region regionNorte = new Region("Norte","(N)",5,10);
    private Region regionSur = new Region("Sur","(S)",7,14);
    private Region regionEste = new Region("Este","(E)",4.5,11.25);
    
    public ventana() {
        initComponents();        
        cambiarPanel(log);
        panelOpciones.setVisible(false);
        this.setTitle("Edu IPC1 D");
        pare.setRegiones(regionNorte, regionSur, regionEste);
    }
    
    private void cambiarPanel(javax.swing.JPanel miPanel){
        miPanel.setSize(720,380);
        miPanel.setLocation(0,0);        
        panelBase.removeAll();
        panelBase.add(miPanel);
        panelBase.revalidate();
        panelBase.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBase = new javax.swing.JPanel();
        panelAbajo = new javax.swing.JPanel();
        ingresologin = new javax.swing.JButton();
        etiquetaError = new javax.swing.JLabel();
        panelOpciones = new javax.swing.JPanel();
        mostrarProductos = new javax.swing.JButton();
        mostrarCodigos = new javax.swing.JButton();
        irAProducto = new javax.swing.JButton();
        irADescuento = new javax.swing.JButton();
        ventas = new javax.swing.JButton();
        reportes = new javax.swing.JButton();
        irACuenta = new javax.swing.JButton();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBase.setBackground(new java.awt.Color(51, 102, 0));

        javax.swing.GroupLayout panelBaseLayout = new javax.swing.GroupLayout(panelBase);
        panelBase.setLayout(panelBaseLayout);
        panelBaseLayout.setHorizontalGroup(
            panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 973, Short.MAX_VALUE)
        );
        panelBaseLayout.setVerticalGroup(
            panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );

        panelAbajo.setBackground(new java.awt.Color(0, 153, 153));

        ingresologin.setText("Ingresar");
        ingresologin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresologinActionPerformed(evt);
            }
        });

        etiquetaError.setText("...");

        javax.swing.GroupLayout panelAbajoLayout = new javax.swing.GroupLayout(panelAbajo);
        panelAbajo.setLayout(panelAbajoLayout);
        panelAbajoLayout.setHorizontalGroup(
            panelAbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAbajoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(ingresologin)
                .addGap(18, 18, 18)
                .addComponent(etiquetaError)
                .addContainerGap(338, Short.MAX_VALUE))
        );
        panelAbajoLayout.setVerticalGroup(
            panelAbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAbajoLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(panelAbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingresologin)
                    .addComponent(etiquetaError))
                .addGap(32, 32, 32))
        );

        panelOpciones.setBackground(new java.awt.Color(153, 153, 153));

        mostrarProductos.setText("Mostrar Productos");
        mostrarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarProductosActionPerformed(evt);
            }
        });

        mostrarCodigos.setText("Mostrar Codigos");
        mostrarCodigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarCodigosActionPerformed(evt);
            }
        });

        irAProducto.setText("Volver a Producto");
        irAProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irAProductoActionPerformed(evt);
            }
        });

        irADescuento.setText("Volver a Cupones");
        irADescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irADescuentoActionPerformed(evt);
            }
        });

        ventas.setText("Ventas");
        ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventasActionPerformed(evt);
            }
        });

        reportes.setText("Generar Reportes");
        reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportesActionPerformed(evt);
            }
        });

        irACuenta.setText("Mi Cuenta");
        irACuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irACuentaActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOpcionesLayout = new javax.swing.GroupLayout(panelOpciones);
        panelOpciones.setLayout(panelOpcionesLayout);
        panelOpcionesLayout.setHorizontalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(irAProducto)
                    .addComponent(irADescuento))
                .addGap(18, 18, 18)
                .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOpcionesLayout.createSequentialGroup()
                        .addComponent(mostrarProductos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(irACuenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ventas))
                    .addGroup(panelOpcionesLayout.createSequentialGroup()
                        .addComponent(mostrarCodigos)
                        .addGap(18, 18, 18)
                        .addComponent(salir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(reportes)))
                .addContainerGap())
        );
        panelOpcionesLayout.setVerticalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(irAProducto)
                    .addComponent(mostrarProductos)
                    .addComponent(ventas)
                    .addComponent(irACuenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(irADescuento)
                    .addComponent(mostrarCodigos)
                    .addComponent(reportes)
                    .addComponent(salir))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelAbajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAbajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresologinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresologinActionPerformed
        // TODO add your handling code here:
        
        for(int i=0; i<pcue.getListaCuentas().size(); i++){
            Cuenta temporal = new Cuenta();
            temporal = pcue.getListaCuentas().get(i);
            
            if(log.getUsuario().equals(temporal.getUsuario()) && log.getClave().equals(temporal.getContraseña())){
                if(temporal.getEsAdmin()){
                    // panen para admin
                    rutaFotoActual=temporal.getRutaFoto();                
                    log.resetearCampos();
                    cambiarPanel(ppro);
                    panelAbajo.setVisible(false);
                    panelOpciones.setVisible(true);
                    etiquetaError.setText("...");
                    break;
                }else{
                    // panel usuario
                    System.out.println("usuario normal");
                }                
            }else{
                etiquetaError.setText("Usuario o Clave incorrectas, intente nuevamente");
            }            
        }
        
                      
    }//GEN-LAST:event_ingresologinActionPerformed

    private void ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventasActionPerformed
        // TODO add your handling code here:
        pv.setListaProductos(ppro.getListaProductos());
        pv.crearListaDesplegable();
        cambiarPanel(pv);
    }//GEN-LAST:event_ventasActionPerformed

    private void mostrarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarProductosActionPerformed
        // TODO add your handling code here:
        String textoProductos="<html><head></head><body><table><tr><th>Nombre</th><th>Precio</th></tr>";        
        for(int i=0; i<ppro.getListaProductos().size();i++){
            Producto temporal = new Producto();
            temporal = ppro.getListaProductos().get(i);            
            textoProductos = textoProductos+"<tr><td>"+temporal.getNombre()+"</td><td>"+temporal.getPrecio()+"</td></tr>";            
        }
        
        textoProductos=textoProductos+"</table></body></html>";
        
        pmpro.setTextArea(textoProductos);
        cambiarPanel(pmpro);
    }//GEN-LAST:event_mostrarProductosActionPerformed

    private void irADescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irADescuentoActionPerformed
        // TODO add your handling code here:
        cambiarPanel(pcup);
    }//GEN-LAST:event_irADescuentoActionPerformed

    private void irAProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irAProductoActionPerformed
        // TODO add your handling code here:
        cambiarPanel(ppro);
    }//GEN-LAST:event_irAProductoActionPerformed

    private void irACuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irACuentaActionPerformed
        // TODO add your handling code here:        
        cambiarPanel(pcue);
        pcue.fotoActual(rutaFotoActual);        
    }//GEN-LAST:event_irACuentaActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        cambiarPanel(log);
        panelAbajo.setVisible(true);
        panelOpciones.setVisible(false);
    }//GEN-LAST:event_salirActionPerformed

    private void reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportesActionPerformed
        // TODO add your handling code here:
        cambiarPanel(pare);
    }//GEN-LAST:event_reportesActionPerformed

    private void mostrarCodigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarCodigosActionPerformed
        // TODO add your handling code here:
        regionNorte = pare.getNorte();
        pru.setNorte("Nombre: "+regionNorte.getNombre()+" Codigo: "+regionNorte.getCodigo()+" Precio Estandar: "+regionNorte.getPrecioEstandar()+" Precio Especial: "+regionNorte.getPrecioEspecial());
        cambiarPanel(pru);
    }//GEN-LAST:event_mostrarCodigosActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiquetaError;
    private javax.swing.JButton ingresologin;
    private javax.swing.JButton irACuenta;
    private javax.swing.JButton irADescuento;
    private javax.swing.JButton irAProducto;
    private javax.swing.JButton mostrarCodigos;
    private javax.swing.JButton mostrarProductos;
    private javax.swing.JPanel panelAbajo;
    private javax.swing.JPanel panelBase;
    private javax.swing.JPanel panelOpciones;
    private javax.swing.JButton reportes;
    private javax.swing.JButton salir;
    private javax.swing.JButton ventas;
    // End of variables declaration//GEN-END:variables
}
