/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ejemplopoo.paneles;

import ejemplopoo.elementos.Producto;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edush
 */
public class panelVentas extends javax.swing.JPanel {

    /**
     * Creates new form panelVentas
     */
    public panelVentas() {
        initComponents();
        DefaultTableModel model = (DefaultTableModel) tablaVentas.getModel();
        model.setRowCount(0);
        model.setColumnIdentifiers(new Object[] { "Producto","Precio unitario", "Cantidad", "Subtotal" });
        tablaVentas.setModel(model);
    }
    
    public void crearListaDesplegable(){
        listaDesplegableProductos.removeAllItems();
        for(int i=0; i<listaProductos.size();i++){
            Producto temporal = new Producto();
            temporal = listaProductos.get(i);
            //textoProductos = textoProductos+"Producto: "+temporal.getNombre()+" -> Precio: "+temporal.getPrecio()+'\n';
            listaDesplegableProductos.addItem(temporal.getNombre());            
            //System.out.println("Producto: "+temporal.getNombre()+" -> Precio: "+temporal.getPrecio());
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listaDesplegableProductos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVentas = new javax.swing.JTable();
        agregar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        textoTotal = new javax.swing.JLabel();
        vaciar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 153, 153));

        listaDesplegableProductos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Producto");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cantidad");

        tablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaVentas);

        agregar.setText("Agregar al carrito");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Total");

        textoTotal.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        textoTotal.setForeground(new java.awt.Color(204, 0, 0));
        textoTotal.setText("0.0");

        vaciar.setText("Vaciar el carrito");
        vaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(textoTotal)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(listaDesplegableProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vaciar)
                            .addComponent(agregar))
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaDesplegableProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(vaciar)
                        .addGap(95, 95, 95)
                        .addComponent(jLabel3)
                        .addGap(9, 9, 9)
                        .addComponent(textoTotal))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:        
        
        for(int i=0; i<listaProductos.size();i++){
            Producto temporal = new Producto();
            temporal = listaProductos.get(i);
            
            if(temporal.getNombre().equals(listaDesplegableProductos.getSelectedItem())){
                DefaultTableModel model = (DefaultTableModel) tablaVentas.getModel();
                int ct= Integer.parseInt(cantidad.getText());
                Object[] rowData = { temporal.getNombre(), temporal.getPrecio(), ct, ct*temporal.getPrecio() };
                model.addRow(rowData);
                total = total+ct*temporal.getPrecio();
                textoTotal.setText(total+"");                
            }
        }        
    }//GEN-LAST:event_agregarActionPerformed

    private void vaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaciarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tablaVentas.getModel();
        model.setRowCount(0);
        model.setColumnIdentifiers(new Object[] { "Producto","Precio unitario", "Cantidad", "Subtotal" });
        tablaVentas.setModel(model);        
        total=0;
        textoTotal.setText(total+"");
    }//GEN-LAST:event_vaciarActionPerformed

    public void setListaProductos(ArrayList <Producto> listaProductos){
        this.listaProductos=listaProductos;
    }

    public double getTotal(){
        return total;
    }
    
    ArrayList <Producto> listaProductos = new ArrayList <Producto>();
    private double total = 0;
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JTextField cantidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> listaDesplegableProductos;
    private javax.swing.JTable tablaVentas;
    private javax.swing.JLabel textoTotal;
    private javax.swing.JButton vaciar;
    // End of variables declaration//GEN-END:variables
}
